### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide   exp /= n

### ISSUE THREAD

**Issue by mariavica** [Phlya/coolpuppy#6]
Hi! I'd like to use coolpuppy but I'm getting this error while executing this example (data from your coolpuppy_paper repositorie. I know it might not make any biological sense, but I just wanted to check if the code works on my computer):

`coolpup.py ./coolpuppy_paper-master/coolers/Scc1-control.10000.cool ./coolpuppy_paper-master/beds/CGI_All_mm9.bed --outdir test `

And I get this:
```
/software/as/el7.2/EasyBuild/CRG/software/Python/3.5.1-foss-2016a/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:root:Namespace(anchor=None, baselist='./coolpuppy_test/coolpuppy_paper-master/beds/CGI_All_mm9.bed', by_window=False, coolfile='./coolpuppy_paper-master/coolers/Scc1-control.10000.cool', coverage_norm=False, excl_chrs='chrY,chrM', expected=None, incl_chrs='all', local=False, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=None, minshift=100000, minsize=None, n_proc=1, nshifts=10, outdir='test', outname='auto', pad=100, rescale=False, rescale_pad=1.0, rescale_size=99, save_all=False, subset=0, unbalanced=False)
Traceback (most recent call last):
  File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.5.1-foss-2016a/bin/coolpup.py", line 11, in <module>
    sys.exit(main())
  File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.5.1-foss-2016a/lib/python3.5/site-packages/coolpuppy/__main__.py", line 142, in main
    raise FileExistsError("Loop(base) coordinate file doesn't exist")
FileExistsError: Loop(base) coordinate file doesn't exist
[marvila@ant-login6 coolpuppy_test]$ coolpup.py ./coolpuppy_paper-master/coolers/Scc1-control.10000.cool ./coolpuppy_paper-master/beds/CGI_All_mm9.bed --outdir test 
/software/as/el7.2/EasyBuild/CRG/software/Python/3.5.1-foss-2016a/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:root:Namespace(anchor=None, baselist='./coolpuppy_paper-master/beds/CGI_All_mm9.bed', by_window=False, coolfile='./coolpuppy_paper-master/coolers/Scc1-control.10000.cool', coverage_norm=False, excl_chrs='chrY,chrM', expected=None, incl_chrs='all', local=False, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=None, minshift=100000, minsize=None, n_proc=1, nshifts=10, outdir='test', outname='auto', pad=100, rescale=False, rescale_pad=1.0, rescale_size=99, save_all=False, subset=0, unbalanced=False)
INFO:root:Nothing to sum up in chromosome 1
INFO:root:Nothing to sum up in chromosome 2
INFO:root:Nothing to sum up in chromosome 3
INFO:root:Nothing to sum up in chromosome 4
INFO:root:Nothing to sum up in chromosome 5
INFO:root:Nothing to sum up in chromosome 6
INFO:root:Nothing to sum up in chromosome 7
INFO:root:Nothing to sum up in chromosome 8
INFO:root:Nothing to sum up in chromosome 9
INFO:root:Nothing to sum up in chromosome 10
INFO:root:Nothing to sum up in chromosome 11
INFO:root:Nothing to sum up in chromosome 12
INFO:root:Nothing to sum up in chromosome 13
INFO:root:Nothing to sum up in chromosome 14
INFO:root:Nothing to sum up in chromosome 15
INFO:root:Nothing to sum up in chromosome 16
INFO:root:Nothing to sum up in chromosome 17
INFO:root:Nothing to sum up in chromosome 18
INFO:root:Nothing to sum up in chromosome 19
INFO:root:Nothing to sum up in chromosome X
/software/as/el7.2/EasyBuild/CRG/software/Python/3.5.1-foss-2016a/lib/python3.5/site-packages/coolpuppy/coolpup.py:329: RuntimeWarning: invalid value encountered in true_divide
  loop /= n
INFO:root:Total number of piled up windows: 0
INFO:root:Nothing to sum up in chromosome 1
INFO:root:Nothing to sum up in chromosome 2
INFO:root:Nothing to sum up in chromosome 3
INFO:root:Nothing to sum up in chromosome 4
INFO:root:Nothing to sum up in chromosome 5
INFO:root:Nothing to sum up in chromosome 6
INFO:root:Nothing to sum up in chromosome 7
INFO:root:Nothing to sum up in chromosome 8
INFO:root:Nothing to sum up in chromosome 9
INFO:root:Nothing to sum up in chromosome 10
INFO:root:Nothing to sum up in chromosome 11
INFO:root:Nothing to sum up in chromosome 12
INFO:root:Nothing to sum up in chromosome 13
INFO:root:Nothing to sum up in chromosome 14
INFO:root:Nothing to sum up in chromosome 15
INFO:root:Nothing to sum up in chromosome 16
INFO:root:Nothing to sum up in chromosome 17
INFO:root:Nothing to sum up in chromosome 18
INFO:root:Nothing to sum up in chromosome 19
INFO:root:Nothing to sum up in chromosome X
/software/as/el7.2/EasyBuild/CRG/software/Python/3.5.1-foss-2016a/lib/python3.5/site-packages/coolpuppy/coolpup.py:348: RuntimeWarning: invalid value encountered in true_divide
  ctrl /= n

```

Do you know which can be the reason? Files in the test directory contain only nan values:
```
head Scc1-control-10.0K_over_CGI_All_10-shifts.np.txt 
nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
```

Many thanks!

**Comment by mariavica** [comment]
(I've added a more simple script)

**Comment by Phlya** [comment]
Hi, thank you for your interest! By default coolpup.py uses balanced data, but the single-nucleus Hi-C datasets are not balanced... I guess I should add a proper error when this occurs, but that must be the reason. Just add `--unbalanced`, and it should work.

**Comment by mariavica** [comment]
Thanks for your fast reply! But sorry, I'm getting the same error

**Comment by Phlya** [comment]
I see, let me look into it...

**Comment by Phlya** [comment]
Right. The chromosomes in snHi-C coolers are named just with numbers, without "chr", but they start with "chr" in the bed file you are using. I'll fix it, but just try a different cooler file right now, perhaps?

**Comment by Phlya** [comment]
If you pull the coolpuppy_paper repo, you'll get snHi-C coolers with normal chromosome names. It then should work normally.

**Comment by Phlya** [comment]
Going to close it, feel free to reopen if you have any more issues. Thanks again for drawing my attention to this.

**Comment by mariavica** [comment]
Great! It's working now! I'll try the code with our coolers and bedfiles, :smiley: !
Many thanks!!!

**Comment by Phlya** [comment]
Good luck, let me know if you have any more problems!
